config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  # root "pages#home"

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  # App Managment
  namespace :admins do
    get 'dashboard', to: 'dashboard#index'
    resources :users
    resources :admins
  end

  # Landing Pages
  root "home#index"
  get "/about", to: "home#about"
  get "/privacy-policy", to: "home#privacy_policy"

  # Contact
  get "/contact", to: "home#contact"
  get "contacts/new", to: "contacts#new"
  post "contacts/create", to: "contacts#create"

  # Access Pages
  resources :blogs, param: :slug do
    # TODO convert blogs id into words/title
    member do
      get 'preview'
    end
  end

  resources :projects, param: :slug do
    # TODO convert projects id into words/title
    member do
      get 'preview'
    end
  end
  

end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_rich_text :content

  extend FriendlyId
  friendly_id :title, use: :slugged

  def self.published_for_user(user)
    if user.present? # Check if the user exist
      all # If user is admin, return all project posts
    else
      self.published # Otherwise, return only published project posts
    end
  end
  
  def self.published # return only published blogs
    where(published: true)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: %i[ index show ]
  before_action :set_project, only: %i[ show edit update destroy preview]
  before_action :get_authors, only: [ :new,:create,:edit]

  # GET /projects or /projects.json
  def index
    @projects = Project.published_for_user(current_user)
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /blogs/1/preview
  def preview
  end
  
  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy!

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.friendly.find(params[:slug])
      @meta_description = @project.title
      @meta_keywords = @project.tags
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :content, :tags, :image_source, :published, :author_id)
    end

    # Get list of authors
    def get_authors 
      @authors = User.all
    end
end

app/views/projects/_form.html.erb
<% if @project.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
    <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: project, class: "contents") do |form| %>
  <div class="space-y-12">
    <div class="border-b border-gray-900/10 pb-12">

      <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
        <div class="col-span-full">
          <%= form.label :title, class: "block text-sm font-medium leading-6 text-gray-900" %>
          <div class="mt-2">
            <%= form.text_field :title, id: "title", autocomplete: "title", class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
          </div>
        </div>

        <div class="col-span-full">
          <%= form.label :content, class: "block text-sm font-medium leading-6 text-gray-900" %>
          <div class="mt-2">
            <%= form.rich_text_area :content, id: "body", rows: 4, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
          </div>
        </div>

        <div class="col-span-full">
          <%= form.label :tags, class: "block text-sm font-medium leading-6 text-gray-900" %>
          <div class="mt-2">
            <%= form.text_field :tags, id: "tags", class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
          </div>
        </div>

        <div class="col-span-full">
          <%= form.label :image_source, class: "block text-sm font-medium leading-6 text-gray-900" %>
          <div class="mt-2">
            <%= form.text_field :image_source, id: "image_source", autocomplete: "image_source", class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
          </div>
        </div>


        <div class="col-span-full">
          <%= form.label :author, class: "block text-sm font-medium leading-6 text-gray-900"%>
          <div class="mt-2">
            <%= form.select :author_id , options_for_select(@authors.map { |author| [author.full_name, author.id]}), 
                  { prompt: "Select an author" },
                  id: :author_id,
                  class: 'block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:max-w-xs sm:text-sm sm:leading-6', 
                  autocomplete: 'author_id' %>
          </div>
        </div>
        
        <div class="relative flex gap-x-3">
          <div class="flex h-6 items-center">
            <%= form.check_box :published, id: "published", class: "h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-600" %>
          </div>
          <div class="text-sm leading-6">
            <%= form.label :publish, class: "font-medium text-gray-900"%>
          </div>
        </div>

      </div>
    </div>
  </div>

  <div class="mt-6 flex items-center justify-end gap-x-6">
    <%= link_to "Cancel", projects_path, class: "text-sm font-semibold leading-6 text-gray-900" %>
    <%= form.submit class: "rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
  </div>
<% end %>

app/views/projects/_preview.html.erb
<div id="<%= dom_id project %>">
  <div class="group relative">
    <div class="relative h-80 w-full overflow-hidden rounded-lg bg-white sm:aspect-h-1 sm:aspect-w-2 lg:aspect-h-1 lg:aspect-w-1 group-hover:opacity-75 sm:h-64">
      <% if project.image_source.present? && valid_link?(project.image_source) %>
        <%= link_to project_path(project.slug) do %>
          <%= image_tag project.image_source, alt: project.title, class: "h-full w-full object-cover object-center object-top" %>
        <% end %>
      <% else %>
        <%= link_to project_path(project.slug) do %>
        <%= image_tag("astro.png", class: "h-full w-full object-cover object-center object-top", alt: "") %>
        <% end %>
      <% end %>
    </div>
    <div class="absolute inset-x-0 bottom-0 bg-white p-4">
      <p class="mt-1 text-base font-semibold text-gray-900">
        <%= link_to project.title.upcase, project %>
      </p>
      <%= render partial: 'home/shared/tags', locals: { tags: project.tags } %>
      
    </div>
  </div>
</div>

app/views/projects/_project.html.erb
<article class="flex mx-auto flex-col items-start justify-between" id="<%= dom_id project %>">
  <h2 class="my-3 text-lg font-semibold leading-6 text-gray-900 group-hover:text-gray-600">
    <%= project.title.upcase %>
  </h2>
  
  <!-- image cover -->
  <div class="relative h-80 w-full overflow-hidden rounded-lg bg-white sm:aspect-h-1 sm:aspect-w-2 lg:aspect-h-1 lg:aspect-w-1 group-hover:opacity-75 sm:h-64">
    <% if project.image_source.present? && valid_link?(project.image_source) %>
      <%= link_to project_path(project.slug) do %>
        <%= image_tag project.image_source, alt: project.title, class: "h-full w-full object-cover object-center object-top" %>
      <% end %>
    <% else %>
      <%= link_to project_path(project.slug) do %>
      <%= image_tag("astro.png", class: "h-full w-full object-cover object-center object-top", alt: "") %>
      <% end %>
    <% end %>
  </div>

  <!-- content -->
  <div class="group relative">
    <%= render partial: 'home/shared/tags', locals: { tags: project.tags } %>
    <p class="mt-5 text-sm leading-6 text-gray-600 trix-content"><%= project.content %></p>
  </div>
  
  <!-- author -->
  <%= render partial:'home/shared/author', locals: { author: project.author } %>
</article>

app/views/projects/edit.html.erb
<div class="bg-gray">
  <%= render "home/shared/header" %>

  <div class="bg-white py-24 sm:py-32">
    <div class="mx-auto md:w-2/3 w-full flex">
      <div class="mx-auto">
        <% if notice.present? %>
          <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
        <% end %>
        <h1 class="font-bold text-4xl">Editing Project</h1>

        <%= render "form", project: @project %>
    
      </div>
    </div>
  </div>
  
  <%= render "home/shared/footer" %> 
</div>

app/views/projects/index.html.erb
<div class="bg-gray-100">
  <%= render "home/shared/header" %>

  <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
    <div class="mx-auto max-w-2xl py-16 sm:py-24 lg:max-w-none lg:py-32">
      <h2 class="text-2xl font-bold text-gray-900">Projects</h2>
      <div class="mt-5 flex justify-end lg:ml-4 lg:mt-0">
        <span class="sm:ml-3">
          <% if current_user %>
            <%= link_to new_project_path, class: "inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" do %>
              <svg class="-ml-0.5 mr-1.5 h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path d="M10.75 6.75a.75.75 0 00-1.5 0v2.5h-2.5a.75.75 0 000 1.5h2.5v2.5a.75.75 0 001.5 0v-2.5h2.5a.75.75 0 000-1.5h-2.5v-2.5z"></path>
              </svg>
              New Project
            <% end %>
          <% end %>
        </span>
      </div>
      <div id="projects" class="mt-6 space-y-12 lg:grid lg:grid-cols-3 lg:gap-x-6 lg:space-y-0">
        <% @projects.each do |project| %>
          <%= render partial: 'preview', locals: { project: project } %>
        <% end %>
      </div>
      <!-- <div class="mt-6 space-y-12 lg:grid lg:grid-cols-3 lg:gap-x-6 lg:space-y-0">
        <div class="group relative">
          <div class="relative h-80 w-full overflow-hidden rounded-lg bg-white sm:aspect-h-1 sm:aspect-w-2 lg:aspect-h-1 lg:aspect-w-1 group-hover:opacity-75 sm:h-64">
            <img src="https://tailwindui.com/img/ecommerce-images/home-page-02-edition-01.jpg" alt="Desk with leather desk pad, walnut desk organizer, wireless keyboard and mouse, and porcelain mug." class="h-full w-full object-cover object-center">
          </div>
          <h3 class="mt-6 text-sm text-gray-500">
            <a href="#">
              <span class="absolute inset-0"></span>
              Desk and Office
            </a>
          </h3>
          <p class="text-base font-semibold text-gray-900">Work from home accessories</p>
        </div>
        <div class="group relative">
          <div class="relative h-80 w-full overflow-hidden rounded-lg bg-white sm:aspect-h-1 sm:aspect-w-2 lg:aspect-h-1 lg:aspect-w-1 group-hover:opacity-75 sm:h-64">
            <img src="https://tailwindui.com/img/ecommerce-images/home-page-02-edition-02.jpg" alt="Wood table with porcelain mug, leather journal, brass pen, leather key ring, and a houseplant." class="h-full w-full object-cover object-center">
          </div>
          <h3 class="mt-6 text-sm text-gray-500">
            <a href="#">
              <span class="absolute inset-0"></span>
              Self-Improvement
            </a>
          </h3>
          <p class="text-base font-semibold text-gray-900">Journals and note-taking</p>
        </div>
        <div class="group relative">
          <div class="relative h-80 w-full overflow-hidden rounded-lg bg-white sm:aspect-h-1 sm:aspect-w-2 lg:aspect-h-1 lg:aspect-w-1 group-hover:opacity-75 sm:h-64">
            <img src="https://tailwindui.com/img/ecommerce-images/home-page-02-edition-03.jpg" alt="Collection of four insulated travel bottles on wooden shelf." class="h-full w-full object-cover object-center">
          </div>
          <h3 class="mt-6 text-sm text-gray-500">
            <a href="#">
              <span class="absolute inset-0"></span>
              Travel
            </a>
          </h3>
          <p class="text-base font-semibold text-gray-900">Daily commute essentials</p>
        </div>
      </div> -->
    </div>
  </div>

  <%= render "home/shared/footer" %>
</div>

app/views/projects/new.html.erb
<div class="bg-gray">
  <%= render "home/shared/header" %>

  <div class="bg-white py-24 sm:py-32">
    <div class="mx-auto md:w-2/3 w-full flex">
      <div class="mx-auto">
        <% if notice.present? %>
          <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
        <% end %>
        <h1 class="font-bold text-4xl">New Project</h1>

        <%= render "form", project: @project %>

      </div>
    </div>
  </div>

  <%= render "home/shared/footer" %>
</div>

app/views/projects/show.html.erb
<div class="bg-gray">
  <%= render "home/shared/header" %>

  <div class="bg-white py-24 sm:py-32">
    <div class="mx-auto md:w-2/3 w-full flex">
      <div class="mx-auto">
        <% if notice.present? %>
          <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
        <% end %>
    
        <%= render @project %>

        <% if current_user %>
          <%= link_to "Edit this project", edit_project_path(@project.slug), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
          <div class="inline-block ml-2">
            <%= button_to "Destroy this project", project_path(@project.slug), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
          </div>
        <% end %>
        <%= link_to "Back to projects", projects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </div>
    </div>    
  </div>
  
  <%= render "home/shared/footer" %> 
</div>