config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  # root "pages#home"

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  # App Managment
  namespace :admins do
    get 'dashboard', to: 'dashboard#index'
    resources :users
    resources :admins
  end

  # Landing Pages
  root "home#index"
  get "/about", to: "home#about"
  get "/privacy-policy", to: "home#privacy_policy"

  # Contact
  get "/contact", to: "home#contact"
  get "contacts/new", to: "contacts#new"
  post "contacts/create", to: "contacts#create"

  # Access Pages
  resources :blogs, param: :slug do
    # TODO convert blogs id into words/title
    member do
      get 'preview'
    end
  end

  resources :projects, param: :slug do
    # TODO convert projects id into words/title
    member do
      get 'preview'
    end
  end
  

end

app/views/admins/admins/_admin.html.erb
<main class="py-12">
  <div class="lg:px-8 md:px-6 px-4 ">
    <div class="opacity-75 border-gray-400 border-dashed border border-lg overflow-hidden relative h-screen">
      <div class="flex max-w-xl flex-col lg:flex-row items-center justify-start mx-auto" id="<%= dom_id admin %>">
        <div class="lg:w-1/2">
          <h2 class="mb-4 text-lg font-semibold">Admin</h2>
          <!-- Directed view to the form -->
          <%= render "form", admin: @admin %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/admins/admins/_admins.html.erb
<main class="py-12">
  <div class="lg:px-8 md:px-6 px-4 my-2">
    <%= link_to new_admins_admin_path, class: "rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50" do %>
      <span class="inline-block">Add Admin</span>
    <% end %>
  </div>  
  <div class="lg:px-8 md:px-6 px-4 mt-4">
    <div class="opacity-75 border-gray-400 border-dashed border border-lg overflow-hidden relative h-screen">
      <ul role="list" class="divide-y divide-gray-100 mx-4 my-2">
        <% @admins.each do |admin| %>
          <%= render partial: 'preview', locals: { admin: admin } %>
        <% end %>
      </ul>
    </div>
  </div>
</main>

app/views/admins/admins/_form.html.erb
<%= form_for(admin, as: :admin, url: admin.persisted? ? admins_admin_path(admin.id) : admins_admins_path, html: { method:
  admin.persisted? ? :put : :post }) do |f| %>
  <%= render "devise/shared/error_messages" , resource: admin %>

    <div class="mb-4">
      <%= render "shared/avatar", resource: admin, class: "block mb-1" %>
      <%= f.file_field :avatar, class: "form-input w-full"%>
    </div>

    <div class="mb-4">
      <%= f.label :first_name, class: "block mb-1" %>
        <%= f.text_field :first_name, class: "form-input w-full" %>
    </div>

    <div class="mb-4">
      <%= f.label :last_name, class: "block mb-1" %>
        <%= f.text_field :last_name, class: "form-input w-full" %>
    </div>

    <div class="mb-4">
      <%= f.label :email, class: "block mb-1" %>
        <%= f.email_field :email, class: "form-input w-full" %>
    </div>

    <div class="mb-4">
      <%= f.label :password, class: "block mb-1" %> <span class="text-sm">(leave blank if you don't want to change
          it)</span>
        <%= f.password_field :password, class: "form-input w-full" , autocomplete: "new-password" %>
          <% if @minimum_password_length %>
            <span class="text-xs">
              <%= @minimum_password_length %> characters minimum
            </span>
            <% end %>
    </div>

    <div class="mb-4">
      <%= f.label :password_confirmation, class: "block mb-1" %>
        <%= f.password_field :password_confirmation, class: "form-input w-full" , autocomplete: "new-password" %>
    </div>

    <div class="flex items-center justify-between">
      <%= link_to "Back", admins_admins_path, class: "ml-2 py-2 px-4 text-gray-600 hover:text-white text-sm rounded hover:bg-gray-700 focus:outline-none focus:bg-gray-600" %>
      <div class="flex items-center">
        <%= f.submit admin.persisted? ? "Update" : "Create" ,
          class: "ml-2 py-2 px-4 text-gray-600 hover:text-white text-sm rounded hover:bg-gray-700 focus:outline-none focus:bg-gray-600"
        %>
<% end %>
        <% if admin.persisted? %>
          <%= button_to "Delete" , admins_admin_path(admin.id), data: {
            confirm: "Are you sure you want to cancel the account?" ,
            turbo_confirm: "Are you sure you want to cancel the account?" }, method: :delete,
            class: "ml-2 py-2 px-4 text-sm text-red-800 hover:text-white hover:bg-red-800" %>
        <% end %>
      </div>
    </div>

<script>
  function togglePasswordField() {
    var passwordFields = document.getElementById("password_fields");
    var confirmationFields = document.getElementById("confirmation_fields");

    if (passwordFields.style.display === "none") {
      passwordFields.style.display = "block";
      confirmationFields.style.display = "block";
    } else {
      passwordFields.style.display = "none";
      confirmationFields.style.display = "none";
    }
  }
</script>

app/views/admins/admins/_preview.html.erb
<a href="<%= edit_admins_admin_path(admin) %>" class="block hover:bg-gray-100">
  <li class="flex justify-between gap-x-6 py-5">
    <div class="flex min-w-0 gap-x-4">
      <%= render "shared/avatar", resource: admin %>
      <div class="min-w-0 flex-auto">
        <p class="text-sm font-semibold leading-6 text-gray-900"><%= "#{admin.first_name} #{admin.last_name}".titleize %></p>
        <p class="mt-1 truncate text-xs leading-5 text-gray-500"><%= admin.email %></p>
      </div>
    </div>
    <div class="hidden shrink-0 sm:flex sm:flex-col sm:items-end">
      <p class="text-sm leading-6 text-gray-900"><%= "Admin" %></p>
      <p class="mt-1 text-xs leading-5 text-gray-500">Last seen <time datetime="<%= admin.updated_at %>"> 3h ago</time></p>
    </div>
  </li>
</a>

app/views/admins/admins/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Admins::Admins#create</h1>
  <p>Find me in app/views/admins/admins/create.html.erb</p>
</div>

app/views/admins/admins/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">Admins::Admins#destroy</h1>
  <p>Find me in app/views/admins/admins/destroy.html.erb</p>
</div>

app/views/admins/admins/edit.html.erb
<div id="admin_admin_dashboard_edit">
  <div class="bg-white">
    <div>
      <%= render "admins/shared/navbar" %>
      <div class="md:pl-72">
        <%= render "admins/shared/header" %>
        <main class="py-12">
          <div class="lg:px-8 md:px-6 px-4 ">
            <div class="opacity-75 border-gray-400 border-dashed border border-lg overflow-hidden relative h-screen">
              <div class="flex max-w-xl flex-col lg:flex-row items-center justify-start mx-auto">
                <div class="lg:w-1/2">
                  <h2 class="mb-4 text-lg font-semibold">Admin Edit</h2>
                  <%= render "form", admin: @admin %>
                </div>
              </div>
            </div>
          </div>
        </main>
      </div>
    </div>
  </div>
</div>

app/views/admins/admins/index.html.erb
<div id="admin_admin_dashboard">
  <div class="bg-white">
    <div>
      <%= render "admins/shared/navbar" %>
      <div class="md:pl-72">
        <%= render "admins/shared/header" %>
        <%= render "admins" %>
      </div>
    </div>
  </div>
</div>

app/views/admins/admins/new.html.erb
<div id="admin_admin_dashboard_new">
  <div class="bg-white">
    <div>
      <%= render "admins/shared/navbar" %>
      <div class="md:pl-72">
        <%= render "admins/shared/header" %>
        <main class="py-12">
          <div class="lg:px-8 md:px-6 px-4 ">
            <div class="opacity-75 border-gray-400 border-dashed border border-lg overflow-hidden relative h-screen">
              <div class="flex max-w-xl flex-col lg:flex-row items-center justify-start mx-auto">
                <div class="lg:w-1/2">
                  <h2 class="mb-4 text-lg font-semibold">New Admin</h2>
                  <%= render "form", admin: @admin %>
                </div>
              </div>
            </div>
          </div>
        </main>
      </div>
    </div>
  </div>
</div>

app/views/admins/admins/show.html.erb
<div id="admin_admin_dashboard_edit">
  <div class="bg-white">
    <div>
      <%= render "admins/shared/navbar" %>
      <div class="md:pl-72">
        <%= render "admins/shared/header" %>
        <%= render @admin %>
      </div>
    </div>
  </div>
</div>

app/views/admins/admins/update.html.erb
<div>
  <h1 class="font-bold text-4xl">Admins::Admins#update</h1>
  <p>Find me in app/views/admins/admins/update.html.erb</p>
</div>