config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  # root "pages#home"

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  # App Managment
  namespace :admins do
    get 'dashboard', to: 'dashboard#index'
    resources :users
    resources :admins
  end

  # Landing Pages
  root "home#index"
  get "/about", to: "home#about"
  get "/privacy-policy", to: "home#privacy_policy"

  # Contact
  get "/contact", to: "home#contact"
  get "contacts/new", to: "contacts#new"
  post "contacts/create", to: "contacts#create"

  # Access Pages
  resources :blogs, param: :slug do
    # TODO convert blogs id into words/title
    member do
      get 'preview'
    end
  end

  resources :projects, param: :slug do
    # TODO convert projects id into words/title
    member do
      get 'preview'
    end
  end
  

end

app/views/admins/shared/_avatar.html.erb
<% if resource.avatar.attached? %>
  <%= image_tag resource.avatar %>
<% else %>
  <%= render "shared/svg/default_profile_mini" %>
<% end %>

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_header.html.erb
<div
  class="lg:px-8 md:px-6 md:gap-x-6 shadow px-4 bg-white border-gray-300 border-b gap-x-4 items-center shrink-0 h-16 flex z-40 top-0 sticky">
  <button type="button" class="lg:hidden bg-white p-2 m-2">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
      stroke="currentColor" aria-hidden="true" class="w-6 h-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5">
      </path>
    </svg></button>
  <div class="bg-gray-900 w-px h-6 lg:hidden" aria-hidden="true"></div>
  <div class="flex lg:gap-6 self-stretch gap-4 flex-1 ">
    <form class="flex flex-1 relative" action="#" method="GET">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true"
        class="text-gray-400 w-5 h-full left-0 inset-y-0 absolute pointer-events-none">
        <path fill-rule="evenodd"
          d="M9 3.5a5.5 5.5 0 100 11 5.5 5.5 0 000-11zM2 9a7 7 0 1112.452 4.391l3.328 3.329a.75.75 0 11-1.06 1.06l-3.329-3.328A7 7 0 012 9z"
          clip-rule="evenodd"></path>
      </svg><input id="search-field"
        class="focus:border-transparent focus:outline-none md:text-sm text-gray-900 pr-0 pl-8 py-0 border-0 w-full h-full block"
        placeholder="Search..." type="search" name="search">
    </form>
    <div class="lg:gap-6 gap-4 items-center flex">
      <button type="button" class="text-gray-400 p-2 m-2 ">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
          stroke="currentColor" aria-hidden="true" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round"
            d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0">
          </path>
        </svg>
      </button>
      <div class="lg:bg-gray-900 lg:w-px lg:h-6 lg:block hidden" aria-hidden="true"></div>
      <div class="relative" data-headlessui-state="">
        <button class="p-1 items-center flex m-1" id="user-menu-button" type="button"
                aria-haspopup="true" aria-expanded="false" data-headlessui-state=""
                onclick="toggleMenu()">  
          <%= render "shared/avatar", resource: current_admin %>
          <span class="lg:items-center lg:flex hidden">
            <span class="color-gray-900 leading-6 font-semibold text-sm ml-4" aria-hidden="true"><%= "#{current_admin.first_name} #{current_admin.last_name}".titleize %></span>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
                  aria-hidden="true" class="text-gray-400 w-5 h-5 ml-2 ">
              <path fill-rule="evenodd"
                    d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z"
                    clip-rule="evenodd"></path>
            </svg>
          </span>
        </button>
        <div class="absolute right-0 z-10 mt-2 w-50 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 border-gray-500 focus:outline-none hidden"
              role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1" aria-hidden="true" id="user-menu">
          <!-- Active: "bg-gray-100", Not Active: "" -->
          <%= link_to "Your Profile", "#yourprofile", class: "block px-4 py-2 text-lg text-gray-700", role: "menuitem", tabindex: "-1", id: "user-menu-item-0" %>
          <%= link_to "Settings", "#setting", class: "block px-4 py-2 text-lg text-gray-700", role: "menuitem", tabindex: "-1", id: "user-menu-item-1" %>
          <%= link_to "Sign out", destroy_admin_session_path , class: "block px-4 py-2 text-lg text-gray-700", role: "menuitem", tabindex: "-1", id: "user-menu-item-2" %>

        </div>
      </div>                         
    </div>
  </div>
</div>
<script>
  function toggleMenu() {
    var menu = document.getElementById("user-menu");
    menu.classList.toggle("hidden");
  }
</script>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/admins/shared/_navbar.html.erb
      <!-- navbar -->
      <div class="hidden fixed inset-0 z-50 w-72 md:flex flex-col md:flex-row bg-gray-800">
        <div class="flex flex-grow flex-col space-y-5 overflow-y-auto bg-gray-800 px-6 pb-4">
          <div class="flex h-16 shrink-0 items-center">
            <div class="flex lg:flex-1">
              <a href="/admins/dashboard" class="-m-1.5 p-1.5">
                <div class="text-4xl font-bold text-white ho  ver:text-gray-400 transition duration-300">
                  JasonMag
                </div>
              </a>
            </div>
          </div>
          <nav class="flex flex-1 flex-col">
            <ul role="list" class="flex flex-1 flex-col gap-y-7">
              <li>
                <ul role="list" class="mx-[-0.5rem]">
                  <li>
                    <a href="/admins/dashboard"
                      class="bg-gray-800 text-white text-opacity-100 flex gap-x-3 rounded-sm p-2 text-xl leading-6 font-medium">
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                        stroke="currentColor" aria-hidden="true" class="h-6 w-6 shrink-0">
                        <path stroke-linecap="round" stroke-linejoin="round"
                          d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25">
                        </path>
                      </svg>
                      Dashboard
                    </a>
                  </li>
                  <li>
                    <a href="/admins/users"
                      class="bg-gray-800 bg-opacity-100 text-white text-opacity-100 flex gap-x-3 rounded-sm p-2 text-xl leading-6 font-medium">
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                        stroke="currentColor" aria-hidden="true" class="h-6 w-6 shrink-0">
                        <path stroke-linecap="round" stroke-linejoin="round"
                          d="M15 19.128a9.38 9.38 0 002.625.372 9.337 9.337 0 004.121-.952 4.125 4.125 0 00-7.533-2.493M15 19.128v-.003c0-1.113-.285-2.16-.786-3.07M15 19.128v.106A12.318 12.318 0 018.624 21c-2.331 0-4.512-.645-6.374-1.766l-.001-.109a6.375 6.375 0 0111.964-3.07M12 6.375a3.375 3.375 0 11-6.75 0 3.375 3.375 0 016.75 0zm8.25 2.25a2.625 2.625 0 11-5.25 0 2.625 2.625 0 015.25 0z">
                        </path>
                      </svg>
                      Users
                    </a>
                  </li>
                  <li>
                    <a href="/admins/admins"
                      class="bg-gray-800 bg-opacity-100 text-white text-opacity-100 flex gap-x-3 rounded-sm p-2 text-xl leading-6 font-medium">
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                        stroke="currentColor" aria-hidden="true" class="h-6 w-6 shrink-0">
                        <path stroke-linecap="round" stroke-linejoin="round"
                          d="M15 19.128a9.38 9.38 0 002.625.372 9.337 9.337 0 004.121-.952 4.125 4.125 0 00-7.533-2.493M15 19.128v-.003c0-1.113-.285-2.16-.786-3.07M15 19.128v.106A12.318 12.318 0 018.624 21c-2.331 0-4.512-.645-6.374-1.766l-.001-.109a6.375 6.375 0 0111.964-3.07M12 6.375a3.375 3.375 0 11-6.75 0 3.375 3.375 0 016.75 0zm8.25 2.25a2.625 2.625 0 11-5.25 0 2.625 2.625 0 015.25 0z">
                        </path>
                      </svg>
                      Admins
                    </a>
                  </li>
                </ul>
              </li>
              <li>
                <div class="text-l leading-6 font-semibold text-gray-100">Other Features</div>
                <ul role="list" class="mx-[-0.5rem]">
                  <li>
                    <a href="#"
                      class="bg-gray-800 text-white text-opacity-100 flex gap-x-3 rounded-sm p-2 text-xl leading-6 font-medium">
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                        stroke="currentColor" aria-hidden="true" class="h-6 w-6 shrink-0">
                        <path stroke-linecap="round" stroke-linejoin="round"
                          d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25">
                        </path>
                      </svg>
                      Team
                    </a>
                  </li>
                  <li>
                    <a href="#"
                      class="bg-gray-800 bg-opacity-100 text-white text-opacity-100 flex gap-x-3 rounded-sm p-2 text-xl leading-6 font-medium">
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                        stroke="currentColor" aria-hidden="true" class="h-6 w-6 shrink-0">
                        <path stroke-linecap="round" stroke-linejoin="round"
                          d="M15 19.128a9.38 9.38 0 002.625.372 9.337 9.337 0 004.121-.952 4.125 4.125 0 00-7.533-2.493M15 19.128v-.003c0-1.113-.285-2.16-.786-3.07M15 19.128v.106A12.318 12.318 0 018.624 21c-2.331 0-4.512-.645-6.374-1.766l-.001-.109a6.375 6.375 0 0111.964-3.07M12 6.375a3.375 3.375 0 11-6.75 0 3.375 3.375 0 016.75 0zm8.25 2.25a2.625 2.625 0 11-5.25 0 2.625 2.625 0 015.25 0z">
                        </path>
                      </svg>
                      Pages
                    </a>
                  </li>
                </ul>
              </li>
              <li class="mt-auto">
                <ul>
                  <li>
                    <a href="#"
                      class="text-white leading-6 font-semibold text-xl p-2 rounded-sm gap-x-3 flex mx-[-0.5rem]">
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                        stroke="currentColor" aria-hidden="true" class="h-6 w-6 shrink-0">
                        <path stroke-linecap="round" stroke-linejoin="round"
                          d="M9.594 3.94c.09-.542.56-.94 1.11-.94h2.593c.55 0 1.02.398 1.11.94l.213 1.281c.063.374.313.686.645.87.074.04.147.083.22.127.324.196.72.257 1.075.124l1.217-.456a1.125 1.125 0 011.37.49l1.296 2.247a1.125 1.125 0 01-.26 1.431l-1.003.827c-.293.24-.438.613-.431.992a6.759 6.759 0 010 .255c-.007.378.138.75.43.99l1.005.828c.424.35.534.954.26 1.43l-1.298 2.247a1.125 1.125 0 01-1.369.491l-1.217-.456c-.355-.133-.75-.072-1.076.124a6.57 6.57 0 01-.22.128c-.331.183-.581.495-.644.869l-.213 1.28c-.09.543-.56.941-1.11.941h-2.594c-.55 0-1.02-.398-1.11-.94l-.213-1.281c-.062-.374-.312-.686-.644-.87a6.52 6.52 0 01-.22-.127c-.325-.196-.72-.257-1.076-.124l-1.217.456a1.125 1.125 0 01-1.369-.49l-1.297-2.247a1.125 1.125 0 01.26-1.431l1.004-.827c.292-.24.437-.613.43-.992a6.932 6.932 0 010-.255c.007-.378-.138-.75-.43-.99l-1.004-.828a1.125 1.125 0 01-.26-1.43l1.297-2.247a1.125 1.125 0 011.37-.491l1.216.456c.356.133.751.072 1.076-.124.072-.044.146-.087.22-.128.332-.183.582-.495.644-.869l.214-1.281z">
                        </path>
                        <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z">
                        </path>
                      </svg>
                      Settings
                    </a>
                  </li>
                </ul>
              </li>
            </ul>
          </nav>
        </div>
      </div>